# Documentation: http://docs.travis-ci.com/user/languages/julia/
notifications:
  email: false

language: julia

os:
  - linux

julia:
  - 1.3

before_install:
- julia --color=yes --project=. -e 'using Pkg; pkg"add https://github.com/wookay/Guo.jl"'
- julia --color=yes --project=. -e 'using Pkg; pkg"dev Jive"'

script:
-              julia --project=. -p2 test/runtests.jl
- JIVE_PROCS=2 julia --project=. -e 'using Pkg; Pkg.test()'
